Skip auditd update for Fedora 39
During package upgrade for Fedora 39 audit fails scriptlet error on
prior version removal with:
error: %preun(audit-3.1.2-4.fc39.x86_64) scriptlet failed, exit status 2

So we hold the package explicitly to skip the issue during image build.